name: Update readme workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 22 * * *' # Runs every day at 10pm
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-blog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Updating blog posts
      uses: gautamkrishnar/blog-post-workflow@master
      with:
        comment_tag_name: BLOG
        feed_list: "https://gabrieltosta.com.br/rss/feed.xml"

  update-youtube:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Update youTube videos
      uses: gautamkrishnar/blog-post-workflow@master
      with:
        comment_tag_name: YOUTUBE
        feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCnn6QwXCmb5kR5rqSQZAo2w"